//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMSPage
    {
        public int CMSPageId { get; set; }
        public int CMSCategory_Id { get; set; }
        public string CMSPageContent { get; set; }
        public string CMSPageHeading { get; set; }
        public System.DateTime AddedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public short Status { get; set; }
    
        public virtual CMS_Category CMS_Category { get; set; }
    }
}
