//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public Feedback()
        {
            this.Answers = new HashSet<Answer>();
        }
    
        public int ReportId { get; set; }
        public int Teacher_Id { get; set; }
        public int Student_Id { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
