//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery
    {
        public int GalleryId { get; set; }
        public string ImageUrl { get; set; }
        public string Description { get; set; }
        public string FriendlyName { get; set; }
        public int Type_Id { get; set; }
        public System.DateTime AddedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public short Status { get; set; }
    
        public virtual GalleryType GalleryType { get; set; }
    }
}
