//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Semester
    {
        public Semester()
        {
            this.Courses = new HashSet<Course>();
            this.Sections = new HashSet<Section>();
        }
    
        public int SemesterId { get; set; }
        public string SemesterName { get; set; }
        public System.DateTime AddedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public short Status { get; set; }
    
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<Section> Sections { get; set; }
    }
}
