//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Reg_Courses = new HashSet<Reg_Courses>();
            this.Teachers = new HashSet<Teacher>();
        }
    
        public int StudentId { get; set; }
        public string RegistrationNumber { get; set; }
        public int Section_Id { get; set; }
        public System.DateTime AddedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public short Status { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string FatherName { get; set; }
        public string CNIC { get; set; }
        public string UserName { get; set; }
        public string Address { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string MobileNumber { get; set; }
        public string LandlineNumber { get; set; }
        public bool Gender { get; set; }
        public int Age { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Reg_Courses> Reg_Courses { get; set; }
        public virtual Section Section { get; set; }
        public virtual ICollection<Teacher> Teachers { get; set; }
    }
}
